"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY =  os.environ.get('SECRET_KEY')
#'django-insecure-utyjh39mmz33m8^66g&bjan%do!tj%cvo^85bqm(2k%qxpz1lg'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS').split(' ')


# Application definition


RECAPTCHA_PUBLIC_KEY = '6LdVLo4qAAAAAJ5AgLv6HUZ3aeMOIonuBXg-H_ra'
RECAPTCHA_PRIVATE_KEY = '6LdVLo4qAAAAABJM3uYCl6WCyFoL3U5mmRZaKAFo'


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',

    'debug_toolbar',
    'django_recaptcha',

    'main',
    'goods',
    'users',
    'carts',
    'orders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/ 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'home',
        'USER': 'home',
        'PASSWORD': 'fibi2019',
        'HOST': 'localhost',
        'PORT': '5432',
        
    }
}
database_url = os.environ.get('DATABASE_URL')
DATABASES['default'] = dj_database_url.parse(database_url)

#postgresql://sneakers_shop_django_render_user:a6aXrlTVdViF0pWNG4B7J9XkVfivFMiy@dpg-cuj7p3btq21c73amc7fg-a.oregon-postgres.render.com/sneakers_shop_django_render
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": BASE_DIR / "cache",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'



STATICFILES_DIRS=[
    BASE_DIR/'static',
]



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL='users.User'

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

MEDIA_URL='media/'

MEDIA_ROOT=BASE_DIR/'media'

LOGIN_URL='/user/login/'

LOGIN_REDIRECT_URL = '/'

STRIPE_PUBLIC_KEY="pk_test_51QQgK0JNffcOYr2oAbELeEIcR3jZDA6eiTv5qRXTDeHfGlide5Y2afllAvT1sPdIfyvkAn2l8xKVxgNQOuacqhWq00YoQ5CxHE"
STRIPE_SECRET_KEY="sk_test_51QQgK0JNffcOYr2oZCJN9gAonzFdPPCteHNoBXGITtiYuqskFcjSu7K44Wv3YTrx0avK2AgdzbDmIBSGFPhOIbOR00eRs4WVWM"
STRIPE_WEBHOOK_SECRET="whsec_c8c92f629b88b8a79af38aaf06606b9fdfa638d308c6ec5bd01f9fc551b921f6"


EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'