# Generated by Django 5.1.1 on 2024-10-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('id',)},
        ),
    ]
