# Generated by Django 5.1.1 on 2024-11-24 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_sizes_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizes',
            name='size_quantity',
        ),
        migrations.CreateModel(
            name='ProductSizeQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='goods.products')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_products', to='goods.sizes')),
            ],
            options={
                'unique_together': {('product', 'size')},
            },
        ),
    ]
