# Generated by Django 5.1.1 on 2024-11-24 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_remove_sizes_size_quantity_productsizequantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
    ]
