# Generated by Django 5.1.1 on 2024-11-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
